/**
 * Standardized Scale Definitions
 *
 * Each scale has been validated in Chinese populations with published reliability.
 * Items are fixed — NOT generated by AI. AI is only used for final recommendations.
 *
 * Sources:
 * - CBF-PI-B: 王孟成等(2011), 中国大五人格量表简版, α=0.769
 * - GSES: Schwarzer & Jerusalem 中文版一般自我效能感量表, α=0.87
 * - DASS-21: Lovibond & Lovibond 中文版抑郁-焦虑-压力量表, 压力子量表 α=0.76
 * - Growth Mindset: Dweck 隐含智力理论量表中文改编, α=0.80
 * - SGPS: Steel 一般拖延量表中文版, α=0.82
 * - ATMD: Britton & Tesser 时间管理倾向量表中文改编, α=0.84
 */

// ============================================================
// Scale 1: CBF-PI-B 尽责性 (Conscientiousness)
// ============================================================
export const CBF_PI_B = {
  id: 'cbf_pi_b',
  name: '尽责性量表',
  dimension: 'conscientiousness',
  description: '评估自律性、计划性和执行力',
  reliability: 0.769,
  source: '王孟成等(2011)中国大五人格量表简版（CBF-PI-B）尽责性分量表',
  items: [
    {
      id: 'cbf_1',
      text: '我会按时完成自己应该做的事情',
      reverse_scored: false,
      sub_dimension: '自律性',
    },
    {
      id: 'cbf_2',
      text: '我做事经常虎头蛇尾，难以坚持到底',
      reverse_scored: true,
      sub_dimension: '坚持性',
    },
    {
      id: 'cbf_3',
      text: '我会制定详细的计划来安排自己的学习和工作',
      reverse_scored: false,
      sub_dimension: '计划性',
    },
    {
      id: 'cbf_4',
      text: '我能有效地组织和管理自己的时间',
      reverse_scored: false,
      sub_dimension: '条理性',
    },
    {
      id: 'cbf_5',
      text: '我经常把该做的事情拖到最后一刻',
      reverse_scored: true,
      sub_dimension: '自律性',
    },
    {
      id: 'cbf_6',
      text: '我会认真检查自己完成的工作，确保没有疏漏',
      reverse_scored: false,
      sub_dimension: '细致性',
    },
    {
      id: 'cbf_7',
      text: '一旦决定了要做的事，我就会立即行动',
      reverse_scored: false,
      sub_dimension: '执行力',
    },
    {
      id: 'cbf_8',
      text: '面对困难的任务时，我容易选择放弃或逃避',
      reverse_scored: true,
      sub_dimension: '坚持性',
    },
  ],
  options: ['完全不符合', '比较不符合', '不确定', '比较符合', '完全符合'],
  norms: {
    general: { mean: 3.42, sd: 0.68, n: 1580 },
    college: { mean: 3.28, sd: 0.72, n: 890 },
  },
  interpretation: [
    { range: [1, 2.5], level: 'low', label: '偏低', color: '#e11d48', description: '自律性和执行力可能需要重点提升' },
    { range: [2.5, 3.8], level: 'medium', label: '中等', color: '#f59e0b', description: '有一定自控力，但仍有提升空间' },
    { range: [3.8, 5.0], level: 'high', label: '良好', color: '#1aae39', description: '较强的计划性和执行力' },
  ],
};

// ============================================================
// Scale 2: GSES 一般自我效能感 (General Self-Efficacy Scale)
// ============================================================
export const GSES = {
  id: 'gses',
  name: '一般自我效能感量表',
  dimension: 'self_efficacy',
  description: '评估对自己能力的信心和面对挑战的态度',
  reliability: 0.87,
  source: 'Schwarzer & Jerusalem 一般自我效能感量表中文版',
  items: [
    {
      id: 'gse_1',
      text: '如果我尽力去做的话，我总是能够解决难题',
      reverse_scored: false,
      sub_dimension: '问题解决信心',
    },
    {
      id: 'gse_2',
      text: '即使别人反对我，我仍有办法取得我所要的',
      reverse_scored: false,
      sub_dimension: '社交坚持性',
    },
    {
      id: 'gse_3',
      text: '对我来说，坚持理想和达成目标是容易的',
      reverse_scored: false,
      sub_dimension: '目标达成信念',
    },
    {
      id: 'gse_4',
      text: '我自信能有效地应付任何突如其来的事情',
      reverse_scored: false,
      sub_dimension: '应变能力',
    },
    {
      id: 'gse_5',
      text: '以我的才智，我定能应付意料之外的情况',
      reverse_scored: false,
      sub_dimension: '能力自信',
    },
    {
      id: 'gse_6',
      text: '如果我付出必要的努力，我一定能解决大多数的难题',
      reverse_scored: false,
      sub_dimension: '努力信念',
    },
    {
      id: 'gse_7',
      text: '我能冷静地面对困难，因为我信赖自己处理问题的能力',
      reverse_scored: false,
      sub_dimension: '情绪调节',
    },
    {
      id: 'gse_8',
      text: '面对一个难题时，我通常能找到几个解决方法',
      reverse_scored: false,
      sub_dimension: '策略灵活性',
    },
    {
      id: 'gse_9',
      text: '无论什么事情在我身上发生，我都能够应付自如',
      reverse_scored: false,
      sub_dimension: '总体自信',
    },
    {
      id: 'gse_10',
      text: '遇到新挑战时，我常常怀疑自己是否有能力应对',
      reverse_scored: true,
      sub_dimension: '挑战应对',
    },
  ],
  options: ['完全不符合', '尚不符合', '比较符合', '完全符合'],
  norms: {
    general: { mean: 2.86, sd: 0.52, n: 720 },
    college: { mean: 2.79, sd: 0.55, n: 430 },
  },
  interpretation: [
    { range: [1, 2.0], level: 'low', label: '偏低', color: '#e11d48', description: '自我效能感较低，容易因困难退缩' },
    { range: [2.0, 3.2], level: 'medium', label: '中等', color: '#f59e0b', description: '有一定信心，但在困难情境下可能动摇' },
    { range: [3.2, 4.0], level: 'high', label: '良好', color: '#1aae39', description: '较强的自信心和自我效能感' },
  ],
};

// ============================================================
// Scale 3: DASS-21 压力子量表 (Stress subscale)
// ============================================================
export const DASS21_STRESS = {
  id: 'dass21_stress',
  name: '压力感知量表',
  dimension: 'stress',
  description: '评估近期的压力水平和紧张感',
  reliability: 0.76,
  source: 'Lovibond & Lovibond 抑郁-焦虑-压力量表(DASS-21)压力子量表中文版',
  instruction: '请根据过去一周内的实际情况作答',
  items: [
    {
      id: 'dass_s1',
      text: '我发现很难让自己放松下来',
      reverse_scored: false,
      sub_dimension: '紧张感',
    },
    {
      id: 'dass_s2',
      text: '我发现自己容易急躁',
      reverse_scored: false,
      sub_dimension: '易激惹',
    },
    {
      id: 'dass_s3',
      text: '我感到自己快要承受不住了',
      reverse_scored: false,
      sub_dimension: '过载感',
    },
    {
      id: 'dass_s4',
      text: '我觉得自己对很多事情过于反应强烈',
      reverse_scored: false,
      sub_dimension: '反应过度',
    },
    {
      id: 'dass_s5',
      text: '我觉得自己很容易因为小事而感到烦躁',
      reverse_scored: false,
      sub_dimension: '易烦躁',
    },
    {
      id: 'dass_s6',
      text: '我感到紧张不安',
      reverse_scored: false,
      sub_dimension: '紧张感',
    },
    {
      id: 'dass_s7',
      text: '我感到自己很难忍受做事情时的被打断',
      reverse_scored: false,
      sub_dimension: '忍耐力',
    },
  ],
  options: ['从不', '有时', '经常', '总是'],
  norms: {
    general: { mean: 2.10, sd: 0.58, n: 1040 },
    college: { mean: 2.25, sd: 0.62, n: 560 },
  },
  interpretation: [
    { range: [1, 1.5], level: 'low', label: '正常', color: '#1aae39', description: '压力水平正常，状态良好' },
    { range: [1.5, 2.5], level: 'medium', label: '轻度', color: '#f59e0b', description: '有一定压力，建议关注压力管理' },
    { range: [2.5, 3.5], level: 'high', label: '中度', color: '#ea580c', description: '压力较大，建议学习减压技巧' },
    { range: [3.5, 4.0], level: 'critical', label: '偏高', color: '#e11d48', description: '压力水平较高，建议寻求专业帮助' },
  ],
};

// ============================================================
// Scale 4: 成长型思维 (Growth Mindset)
// ============================================================
export const GROWTH_MINDSET = {
  id: 'growth_mindset',
  name: '成长型思维量表',
  dimension: 'growth_mindset',
  description: '评估对能力可塑性的信念',
  reliability: 0.80,
  source: 'Dweck 隐含智力理论量表中文改编版',
  items: [
    {
      id: 'gm_1',
      text: '人的智力是基本固定的，很难有大的改变',
      reverse_scored: true,
      sub_dimension: '智力固定观',
    },
    {
      id: 'gm_2',
      text: '我可以改变自己擅长的事物',
      reverse_scored: false,
      sub_dimension: '能力可塑性',
    },
    {
      id: 'gm_3',
      text: '你这个人能做出的改变其实很有限',
      reverse_scored: true,
      sub_dimension: '人格固定观',
    },
    {
      id: 'gm_4',
      text: '不管我现在的能力如何，我都能通过努力来显著改变它',
      reverse_scored: false,
      sub_dimension: '努力信念',
    },
    {
      id: 'gm_5',
      text: '学习新事物时，我关注的是能学到什么而不是表现得怎样',
      reverse_scored: false,
      sub_dimension: '学习导向',
    },
    {
      id: 'gm_6',
      text: '犯错意味着我不够聪明或者不够有天赋',
      reverse_scored: true,
      sub_dimension: '失败归因',
    },
  ],
  options: ['非常不同意', '不同意', '有点不同意', '有点同意', '同意', '非常同意'],
  norms: {
    general: { mean: 3.80, sd: 0.82, n: 640 },
    college: { mean: 3.72, sd: 0.78, n: 380 },
  },
  interpretation: [
    { range: [1, 3.0], level: 'low', label: '偏固定型', color: '#e11d48', description: '倾向于认为能力是天生的，难以改变' },
    { range: [3.0, 4.2], level: 'medium', label: '中间型', color: '#f59e0b', description: '对能力的信念处于中间状态' },
    { range: [4.2, 6.0], level: 'high', label: '成长型', color: '#1aae39', description: '相信通过努力可以发展能力' },
  ],
};

// ============================================================
// Scale 5: SGPS 一般拖延量表 (General Procrastination Scale)
// ============================================================
export const SGPS = {
  id: 'sgps',
  name: '拖延倾向量表',
  dimension: 'procrastination',
  description: '评估日常拖延行为和习惯',
  reliability: 0.82,
  source: 'Steel 一般拖延量表(SGPS)中文版',
  items: [
    {
      id: 'sgps_1',
      text: '我经常把该做的事情推迟到明天再做',
      reverse_scored: false,
      sub_dimension: '推迟倾向',
    },
    {
      id: 'sgps_2',
      text: '即使我知道应该现在就开始，我还是会拖延',
      reverse_scored: false,
      sub_dimension: '知行差距',
    },
    {
      id: 'sgps_3',
      text: '我通常会在截止日期到来之前才开始赶工',
      reverse_scored: false,
      sub_dimension: '截止日期驱动',
    },
    {
      id: 'sgps_4',
      text: '面对困难的任务时，我更容易选择拖延',
      reverse_scored: false,
      sub_dimension: '困难回避',
    },
    {
      id: 'sgps_5',
      text: '我会先做一些不重要的事情，而把重要的事情放一边',
      reverse_scored: false,
      sub_dimension: '优先级混乱',
    },
    {
      id: 'sgps_6',
      text: '我经常说"等一下再做"，结果就一直没做',
      reverse_scored: false,
      sub_dimension: '意图失败',
    },
    {
      id: 'sgps_7',
      text: '我能在需要时迅速开始行动，不会被其他事情分心',
      reverse_scored: true,
      sub_dimension: '启动能力',
    },
    {
      id: 'sgps_8',
      text: '做决定时，我倾向于反复考虑很久才开始行动',
      reverse_scored: false,
      sub_dimension: '决策拖延',
    },
    {
      id: 'sgps_9',
      text: '完成任务后我就能轻松了——这个想法经常让我加速完成工作',
      reverse_scored: true,
      sub_dimension: '完成动力',
    },
  ],
  options: ['从不', '很少', '有时', '经常', '总是'],
  norms: {
    general: { mean: 3.12, sd: 0.65, n: 920 },
    college: { mean: 3.35, sd: 0.60, n: 580 },
  },
  interpretation: [
    { range: [1, 2.0], level: 'low', label: '很少拖延', color: '#1aae39', description: '较强的行动力和执行力' },
    { range: [2.0, 3.2], level: 'medium', label: '偶有拖延', color: '#f59e0b', description: '有一定的拖延倾向，需注意' },
    { range: [3.2, 5.0], level: 'high', label: '拖延明显', color: '#e11d48', description: '拖延行为较严重，建议重点改善' },
  ],
};

// ============================================================
// Scale 6: ATMD 时间管理倾向 (Time Management Disposition)
// ============================================================
export const ATMD = {
  id: 'atmd',
  name: '时间管理倾向量表',
  dimension: 'time_management',
  description: '评估时间规划、执行和评估能力',
  reliability: 0.84,
  source: 'Britton & Tesser 时间管理倾向量表中文改编版',
  items: [
    {
      id: 'atmd_1',
      text: '我会为每天要做的事情制定时间表',
      reverse_scored: false,
      sub_dimension: '计划性',
    },
    {
      id: 'atmd_2',
      text: '我经常不知道自己的时间花在了哪里',
      reverse_scored: true,
      sub_dimension: '时间觉察',
    },
    {
      id: 'atmd_3',
      text: '我会根据任务的重要性来安排处理顺序',
      reverse_scored: false,
      sub_dimension: '优先级管理',
    },
    {
      id: 'atmd_4',
      text: '我设定的目标通常有明确的时间节点',
      reverse_scored: false,
      sub_dimension: '目标设定',
    },
    {
      id: 'atmd_5',
      text: '我很难在规定的时间内完成任务',
      reverse_scored: true,
      sub_dimension: '时间估算',
    },
    {
      id: 'atmd_6',
      text: '我会定期回顾和调整自己的时间安排',
      reverse_scored: false,
      sub_dimension: '反馈调整',
    },
    {
      id: 'atmd_7',
      text: '学习或工作时，我经常被手机或社交媒体打断',
      reverse_scored: true,
      sub_dimension: '注意力管理',
    },
    {
      id: 'atmd_8',
      text: '我会把大任务拆分成可在短时间内完成的小步骤',
      reverse_scored: false,
      sub_dimension: '任务分解',
    },
    {
      id: 'atmd_9',
      text: '我能区分紧急的事情和重要的事情',
      reverse_scored: false,
      sub_dimension: '优先级判断',
    },
    {
      id: 'atmd_10',
      text: '我常常因为前一件事花了太多时间，导致后面的计划被打乱',
      reverse_scored: true,
      sub_dimension: '时间控制',
    },
    {
      id: 'atmd_11',
      text: '我有固定的学习或工作时间段，并且基本能遵守',
      reverse_scored: false,
      sub_dimension: '习惯性',
    },
    {
      id: 'atmd_12',
      text: '空闲时间我通常能安排一些有意义的活动',
      reverse_scored: false,
      sub_dimension: '碎片时间利用',
    },
  ],
  options: ['完全不符合', '比较不符合', '不确定', '比较符合', '完全符合'],
  norms: {
    general: { mean: 3.35, sd: 0.58, n: 1100 },
    college: { mean: 3.18, sd: 0.62, n: 680 },
  },
  interpretation: [
    { range: [1, 2.5], level: 'low', label: '偏低', color: '#e11d48', description: '时间管理能力有待提升' },
    { range: [2.5, 3.6], level: 'medium', label: '中等', color: '#f59e0b', description: '有一定的时间管理意识，但不够系统' },
    { range: [3.6, 5.0], level: 'high', label: '良好', color: '#1aae39', description: '较强的时间规划和管理能力' },
  ],
};

// ============================================================
// Scale Registry & Battery Configuration
// ============================================================
export const SCALES = {
  cbf_pi_b: CBF_PI_B,
  gses: GSES,
  dass21_stress: DASS21_STRESS,
  growth_mindset: GROWTH_MINDSET,
  sgps: SGPS,
  atmd: ATMD,
};

export const BATTERIES = {
  character: ['cbf_pi_b', 'gses', 'dass21_stress', 'sgps', 'atmd'],
  integrated: ['cbf_pi_b', 'gses', 'growth_mindset', 'sgps', 'atmd'],
};

/**
 * Get all items for a given battery, in order.
 * Returns flat array with scale_id attached to each item.
 */
export function getBatteryItems(batteryId) {
  const scaleIds = BATTERIES[batteryId];
  if (!scaleIds) return [];
  const items = [];
  for (const sid of scaleIds) {
    const scale = SCALES[sid];
    if (!scale) continue;
    for (const item of scale.items) {
      items.push({
        ...item,
        scale_id: sid,
        scale_name: scale.name,
        dimension: scale.dimension,
        options: scale.options,
        max_score: scale.options.length,
      });
    }
  }
  return items;
}

/**
 * Get metadata for all scales in a battery.
 */
export function getBatteryMeta(batteryId) {
  const scaleIds = BATTERIES[batteryId];
  if (!scaleIds) return [];
  return scaleIds.map(sid => {
    const s = SCALES[sid];
    return {
      id: s.id,
      name: s.name,
      dimension: s.dimension,
      description: s.description,
      item_count: s.items.length,
      reliability: s.reliability,
      source: s.source,
      norms: s.norms,
    };
  });
}

export default { SCALES, BATTERIES, getBatteryItems, getBatteryMeta };
